# Generated by Django 2.1.3 on 2019-01-03 20:50

from django.conf import settings
from django.db import migrations, models
import poll.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('poll', '0003_auto_20181215_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=models.SET(poll.models.Poll.get_sentinel_user), to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
