# Generated by Django 2.1.3 on 2019-02-02 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0005_auto_20190202_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='poll.Question', verbose_name='question'),
        ),
    ]
